modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/ElytraLimiter/issues"
license="MIT"

[[mods]]
modId="elytralimiter"
version="${file.jarVersion}"
displayName="Elytra Limiter"
displayURL="https://www.curseforge.com/minecraft/mc-mods/elytra-limiter"
authors="Mrbysco"
description='''
Allows limiting elytra usage to specific dimensions
'''
[[dependencies.elytralimiter]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.elytralimiter]]
modId="neoforge"
type="required"
versionRange="[21.1.1,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="elytralimiter.mixins.json"